--seed.sql
INSERT INTO Salon(Naziv,Adresa,BrojTelefona,Email,WebAdresa,BrRacuna,Pib,MaticniBr,Obrisan)
VALUES('Moj Salon','Kralja Petra II, br 41','060-553/2313','example@mojsalon.com','www.mojsalon.com','58267581764',123456789,987654321,0)
----------------------------------------------------------
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Ostalo',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Polica',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Krevet',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Sto',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Stolica',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Dvosed',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Trosed',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Lampa',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Kuhinji element',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Hoklica',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Kredenac',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Tv Komoda',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Klupa',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Cipelarnik',0);
INSERT INTO TipNamestaja(Naziv,Obrisan)
VALUES('Fotelja',0);
----------------------------------------------------------
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(2,'Ultra polica','UL1PO',1200.5,52,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(3,'Crni krevet','CR2KR',5000,22,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(4,'Sto 123','ST11ST',2000,135,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(5,'Lazy bag black','LA44ST',6700,157,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(3,'Leteci krevet','LE1PO',12300.5,12,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(3,'Vodeni krevet','VO2KR',2300,32,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(4,'Sto Crni','ST11ST',1500,53,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(5,'Lazy bag','LA3ST',3700,27,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(7,'Crni trosed','CR3TR',6700,27,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(6,'Crni dvosed','CR31DV',4500,123,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(4,'Pisaci sto','PI22ST',4200,123,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(14,'Crni cipelarnik','CR341CI',2500,23,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(12,'Tv komoda metalik','TV212ST',4200,123,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(8,'Lampa crna','LA31LA',1800,21,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(8,'Lampa bela','LA31LA',1800,42,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(8,'Lampa siva','LA31LA',1800,123,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(8,'Lampa zuta','LA31LA',1800,44,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(8,'Lampa zelena','LA31LA',1800,77,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(15,'Fotelja roza','FO541FO',7500,84,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(15,'Fotelja zelena','FO111FO',4500,26,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(15,'Fotelja crvena','FO271FO',7500,65,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(15,'Fotelja leteca','FO473FO',7500,22,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(15,'Fotelja kozna','FO984FO',17200,31,0)
INSERT INTO Namestaj(TipNamestajaId,Naziv,Sifra,Cena,Kolicina,Obrisan)
VALUES(15,'Fotelja masazna','FO999FO',21500,11,0)
----------------------------------------------------------
INSERT INTO DodatnaUsluga(Naziv,Cena,Obrisan)
VALUES('Prevoz',2000,0)
INSERT INTO DodatnaUsluga(Naziv,Cena,Obrisan)
VALUES('Pakovanje',400,0)
INSERT INTO DodatnaUsluga(Naziv,Cena,Obrisan)
VALUES('Sastavljanje',250,0)
INSERT INTO DodatnaUsluga(Naziv,Cena,Obrisan)
VALUES('Garancija +1god',2500,0)
INSERT INTO DodatnaUsluga(Naziv,Cena,Obrisan)
VALUES('Garancija +2god',4500,0)
INSERT INTO DodatnaUsluga(Naziv,Cena,Obrisan)
VALUES('Garancija +3god',7000,0)
INSERT INTO DodatnaUsluga(Naziv,Cena,Obrisan)
VALUES('Servisiranje',2000,0)
----------------------------------------------------------
INSERT INTO Korisnik(Ime,Prezime,KorisnickoIme,Lozinka,TipKorisnika,Obrisan)
VALUES('Zoran','Jovanovic','123','123',1,0)
INSERT INTO Korisnik(Ime,Prezime,KorisnickoIme,Lozinka,TipKorisnika,Obrisan)
VALUES('Goran','Jovanovic','1234','1234',2,0)
INSERT INTO Korisnik(Ime,Prezime,KorisnickoIme,Lozinka,TipKorisnika,Obrisan)
VALUES('Jovan','Jovanovic','321','321',1,0)
INSERT INTO Korisnik(Ime,Prezime,KorisnickoIme,Lozinka,TipKorisnika,Obrisan)
VALUES('Maja','Pejic','4213','4213',1,0)
INSERT INTO Korisnik(Ime,Prezime,KorisnickoIme,Lozinka,TipKorisnika,Obrisan)
VALUES('Pero','Stevo','1111','1111',2,0)
INSERT INTO Korisnik(Ime,Prezime,KorisnickoIme,Lozinka,TipKorisnika,Obrisan)
VALUES('Zarko','Crnomarkovic','2222','2222',1,0)
INSERT INTO Korisnik(Ime,Prezime,KorisnickoIme,Lozinka,TipKorisnika,Obrisan)
VALUES('Sreten','Adzic','1212','1212',2,0)
INSERT INTO Korisnik(Ime,Prezime,KorisnickoIme,Lozinka,TipKorisnika,Obrisan)
VALUES('Jelena Elizabeta','Konstantinovic','3333','3333',2,0)
INSERT INTO Korisnik(Ime,Prezime,KorisnickoIme,Lozinka,TipKorisnika,Obrisan)
VALUES('Mirko','Brkic','4444','4444',1,0)
----------------------------------------------------------
INSERT INTO ProdajaNamestaja(Kupac,BrRacuna,DatumProdaje,UkupnaCena,Obrisan)
VALUES('Zoran','12131415','2017/12/25',66343,0)
INSERT INTO ProdajaNamestaja(Kupac,BrRacuna,DatumProdaje,UkupnaCena,Obrisan)
VALUES('Goran','51413121','2017/12/24',25321,0)
INSERT INTO ProdajaNamestaja(Kupac,BrRacuna,DatumProdaje,UkupnaCena,Obrisan)
VALUES('Tesla','4141412','2018/1/2',75543,0)
INSERT INTO ProdajaNamestaja(Kupac,BrRacuna,DatumProdaje,UkupnaCena,Obrisan)
VALUES('Rambo','3624224','2018/1/1',63433,0)
INSERT INTO ProdajaNamestaja(Kupac,BrRacuna,DatumProdaje,UkupnaCena,Obrisan)
VALUES('Jelena','4141412','2018/1/2',33522,0)
INSERT INTO ProdajaNamestaja(Kupac,BrRacuna,DatumProdaje,UkupnaCena,Obrisan)
VALUES('Stevo','3624224','2018/1/3',41423,0)
INSERT INTO ProdajaNamestaja(Kupac,BrRacuna,DatumProdaje,UkupnaCena,Obrisan)
VALUES('Marija','4141412','2018/1/2',86765,0)
INSERT INTO ProdajaNamestaja(Kupac,BrRacuna,DatumProdaje,UkupnaCena,Obrisan)
VALUES('Jovo','3624224','2018/1/4',43211,0)

----------------------------------------------------------
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(1,1,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(1,2,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(1,3,0)
--
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(2,1,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(2,2,0)
--
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(3,4,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(3,5,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(3,1,0)
--
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(4,1,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(4,2,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(4,3,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(4,5,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(4,4,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(4,7,0)
--
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(5,1,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(5,2,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(5,3,0)
--
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(6,3,0)
--
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(7,3,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(7,5,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(7,4,0)
INSERT INTO ProdataDodatnaUsluga(ProdajaId,DodatnaUslugaId,Obrisan)
VALUES(7,7,0)
-------------------------------------------------------------------------------
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(1,1,2,123.5,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(1,2,2,5000,0)
--
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(2,3,21,2010,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(2,4,23,5025,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(2,5,22,8502.52,0)
--
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(3,6,42,22555,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(3,7,22,72525,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(3,8,29,63232,0)
--
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(4,9,42,245512,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(4,10,2,4888,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(4,11,12,14155,0)
--
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(5,12,2,7234,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(5,13,2,5232,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(5,14,2,8222,0)
--
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(6,2,1,4122,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(6,6,22,44412,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(6,11,13,12222,0)
--
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(7,1,1,5555,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(7,13,22,63222,0)
--
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(8,4,1,4111,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(8,11,22,22412,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(8,1,4,12552,0)
INSERT INTO JedinicaProdaje(ProdajaId,NamestajId,Kolicina,Cena,Obrisan)
VALUES(8,5,22,52241,0)
----------------------------------------------------------
INSERT INTO Akcija(Naziv,DatumPocetak,DatumKraj,Obrisan)
VALUES('Novogodisnja akcija','1/1/2016','2/2/2018',0)
INSERT INTO Akcija(Naziv,DatumPocetak,DatumKraj,Obrisan)
VALUES('Zimska akcija','12/2/2016','3/13/2018',0)
INSERT INTO Akcija(Naziv,DatumPocetak,DatumKraj,Obrisan)
VALUES('Prosla Akcija','12/2/2016','3/13/2017',0)
INSERT INTO Akcija(Naziv,DatumPocetak,DatumKraj,Obrisan)
VALUES('Nova Prosla Akcija','12/12/2017','2/2/2018',0)
----------------------------------------------------------
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(1,1,15,0)
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(1,2,11,0)
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(1,3,17,0)
--
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(2,4,25,0)
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(2,5,31,0)
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(2,6,47,0)
--
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(3,7,25,0)
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(3,8,31,0)
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(3,9,47,0)
--
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(4,7,11,0)
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(4,8,11,0)
INSERT INTO NaAkciji(IdAkcije,IdNamestaja,Popust,Obrisan)
VALUES(4,9,11,0)
----------------------------------------------------------
